tunnel: 9d279e74-afc1-4150-8f1e-333e7e691212
credentials-file: C:\Users\leade\.cloudflared\9d279e74-afc1-4150-8f1e-333e7e691212.json
ingress:
  - hostname: api.leadertechnology.shop
    service: https://localhost:1337
    originRequest:
      noTLSVerify: true
  - service: http_status:404
